### ISSUE TITLE
Spam check not working in test/production?

### ISSUE THREAD

**Issue by evendir** [heartcombo/mail_form#50]
As far as I can tell, at the moment the spam check works properly in development (raising an error), but forms will deliver as normal even if a captcha field is populated in other environments.

This wasn't the case in an older project running 1.5.1, but is the case in 1.6.0

**Comment by Bespinoza10** [comment]
I and several clients have been receiving SPAM Mail from their contact form with Mail_Form. Seems like the purpose of having the nickname hidden field is not really working. Any suggestions?

**Comment by Afoster2** [comment]
I have also noticed a rise in SPAM email coming from contact forms using Mail_Form. Have there been any updates on this?

**Comment by josevalim** [comment]
There is nothing we can do this on this really. If the bots are becoming smart enough to not fill in hidden fields, then we have been beaten. :D 

You may try hidding the field in others way. Maybe list it as an actual text by hide it with CSS. But it may that  the technique as a whole at this point is outdated and throttling the e-mail through an actual spam detector may be the best way to go.

**Comment by carlosantoniodasilva** [comment]
@evendir @mxmbadev @Afoster2 since this is sort of an old one, I'm not sure which version you were using, and/or if you were using `MailForm::Base` or including `MailForm::Delivery` in an Active Record like object, but if it was the latter, it seems this has been broken for a while, see #56 (more specifically https://github.com/heartcombo/mail_form/issues/56#issuecomment-683151041).

That's really the only thing I can think of, that a bug in the callback logic wasn't halting when the spam/captcha field was being filled. Other than that, there's really not much else we can do like José mentioned above.

Let me know if you've been able to fix the situation on your case, or if what I mentioned above makes sense and could help in your case, in which case I'll ask you to try master (I should be releasing a new version soon as well). I'll go ahead and close this one preemptively, but happy to continue the discussion and reopen if needed.
